-- GVI International — Supabase / PostgreSQL
-- Exécuter ce script dans Supabase > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  role text not null default 'collaborator' check (role in ('admin','collaborator')),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.parcels (
  id text primary key,
  client text not null,
  tel text,
  date date not null,
  origin text,
  destination text not null,
  destinataire text,
  tel_dest text,
  qty integer not null default 1,
  type text,
  weight numeric(12,2) not null default 0,
  price numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  declared numeric(12,2) not null default 0,
  status text not null default 'Réceptionné',
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tariffs (
  id bigint generated by default as identity primary key,
  destination text not null unique,
  price numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

insert into public.tariffs(destination, price) values ('Ghana', 90)
on conflict (destination) do update set price = excluded.price;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and approved = true
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, full_name, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name',''), coalesce(new.email,''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.parcels enable row level security;
alter table public.tariffs enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());

drop policy if exists "admin profiles write" on public.profiles;
create policy "admin profiles write" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "approved users read parcels" on public.parcels;
create policy "approved users read parcels" on public.parcels for select to authenticated
using (exists(select 1 from public.profiles p where p.id = auth.uid() and p.approved = true));

drop policy if exists "users insert parcels" on public.parcels;
create policy "users insert parcels" on public.parcels for insert to authenticated
with check (created_by = auth.uid());

drop policy if exists "owners update parcels" on public.parcels;
create policy "owners update parcels" on public.parcels for update to authenticated
using (created_by = auth.uid() or public.is_admin())
with check (created_by = auth.uid() or public.is_admin());

drop policy if exists "admin delete parcels" on public.parcels;
create policy "admin delete parcels" on public.parcels for delete to authenticated using (public.is_admin());

drop policy if exists "approved users read tariffs" on public.tariffs;
create policy "approved users read tariffs" on public.tariffs for select to authenticated
using (exists(select 1 from public.profiles p where p.id = auth.uid() and p.approved = true));

drop policy if exists "admin tariffs write" on public.tariffs;
create policy "admin tariffs write" on public.tariffs for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Après avoir créé votre premier compte dans Supabase Auth,
-- récupérez son UUID puis exécutez :
-- update public.profiles set role='admin' where id='VOTRE-UUID';

create or replace function public.next_parcel_id()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  prefix text := 'GVI-' || to_char(current_date, 'YYMMDD') || '-';
  n integer;
begin
  perform pg_advisory_xact_lock(hashtext(prefix));
  select coalesce(max(substring(id from '[0-9]+$')::integer),0) + 1
  into n from public.parcels where id like prefix || '%';
  return prefix || lpad(n::text,5,'0');
end;
$$;

grant execute on function public.next_parcel_id() to authenticated;


-- Migration pour une base existante :
alter table public.profiles add column if not exists email text not null default '';
update public.profiles p set email = coalesce(u.email,'') from auth.users u where u.id = p.id and coalesce(p.email,'') = '';

-- GVI V1.5 — gestion des collaborateurs depuis l'application
-- La clé service_role ne doit jamais être utilisée dans le navigateur.
-- Les opérations Auth administrateur sont réalisées par l'Edge Function manage-collaborators.

-- Pour une base existante, la colonne email est ajoutée sans supprimer les données.
alter table public.profiles add column if not exists email text not null default '';

update public.profiles p
set email = coalesce(u.email, '')
from auth.users u
where u.id = p.id
  and coalesce(p.email, '') = '';

-- Le profil créé automatiquement reprend aussi l'e-mail Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, full_name, email, role, approved)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    coalesce(new.email,''),
    'collaborator',
    true
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = case
        when excluded.full_name <> '' then excluded.full_name
        else public.profiles.full_name
      end;
  return new;
end;
$$;
